// Writes lib/core/config/firebase_options.dart from the Firebase configs:
//  - android/app/google-services.json  (firebase apps:sdkconfig ANDROID ...)
//  - the web app config                (firebase apps:sdkconfig WEB ...)
// These are public app identifiers, not secrets (see firebase.google.com/docs/projects/api-keys).
//
//   node tool/write_firebase_options.js <webAppId> <projectId>
const fs = require('fs');
const { execSync } = require('child_process');

const [webAppId, project] = process.argv.slice(2);
const g = JSON.parse(fs.readFileSync('android/app/google-services.json', 'utf8'));
const client = g.client.find(
  (c) => c.client_info.android_client_info.package_name === 'com.godoctor.godoctor_app',
);
const out = execSync(`firebase apps:sdkconfig WEB ${webAppId} --project ${project}`).toString();
const web = JSON.parse(out.slice(out.indexOf('{'), out.lastIndexOf('}') + 1));

const dart = `// Generated by tool/write_firebase_options.js from the Firebase project
// "${project}". Public app identifiers, not secrets. Regenerate if the
// Firebase apps change.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  /// Options for this platform, or null where push isn't set up (desktop).
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) return web;
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      _ => null,
    };
  }

  static const android = FirebaseOptions(
    apiKey: '${client.api_key[0].current_key}',
    appId: '${client.client_info.mobilesdk_app_id}',
    messagingSenderId: '${g.project_info.project_number}',
    projectId: '${g.project_info.project_id}',
    storageBucket: '${g.project_info.storage_bucket}',
  );

  static const web = FirebaseOptions(
    apiKey: '${web.apiKey}',
    appId: '${web.appId}',
    messagingSenderId: '${web.messagingSenderId}',
    projectId: '${web.projectId}',
    authDomain: '${web.authDomain}',
    storageBucket: '${web.storageBucket}',
  );
}
`;
fs.writeFileSync('lib/core/config/firebase_options.dart', dart);

// The web service worker needs the same web config.
const sw = `// Firebase Cloud Messaging service worker: shows GoDoctor notifications
// when the web app is in the background or closed. Generated by
// tool/write_firebase_options.js (public identifiers, not secrets).
importScripts('https://www.gstatic.com/firebasejs/10.13.2/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.13.2/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(
  {
    apiKey: web.apiKey,
    appId: web.appId,
    messagingSenderId: web.messagingSenderId,
    projectId: web.projectId,
    authDomain: web.authDomain,
    storageBucket: web.storageBucket,
  },
  null,
  2,
)});

// Notification messages are displayed automatically; tapping one opens
// (or focuses) the app, which then routes to the right screen.
firebase.messaging();
`;
fs.writeFileSync('web/firebase-messaging-sw.js', sw);
console.log('wrote lib/core/config/firebase_options.dart and web/firebase-messaging-sw.js');
