// Generated by tool/write_firebase_options.js from the Firebase project
// "godoctor-ke". Public app identifiers, not secrets. Regenerate if the
// Firebase apps change.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  /// Options for this platform, or null where push isn't set up (desktop).
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) return web;
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      _ => null,
    };
  }

  static const android = FirebaseOptions(
    apiKey: 'AIzaSyBWa44PF7KHTT_qj_9wtrt8DVD9wdhB96I',
    appId: '1:827666475986:android:4abb79b2f975ae26e1f60b',
    messagingSenderId: '827666475986',
    projectId: 'godoctor-ke',
    storageBucket: 'godoctor-ke.firebasestorage.app',
  );

  static const web = FirebaseOptions(
    apiKey: 'AIzaSyDiyxIPAUGSIPzn0_xSLxEBRX89rk4vXII',
    appId: '1:827666475986:web:37ca4da6c14d2055e1f60b',
    messagingSenderId: '827666475986',
    projectId: 'godoctor-ke',
    authDomain: 'godoctor-ke.firebaseapp.com',
    storageBucket: 'godoctor-ke.firebasestorage.app',
  );
}
